#!/bin/bash

DATA_DIR=/var/lib/mysql

if [[ ! -e ${DATA_DIR} ]]; then
  echo Creating new Percona database...
  install -dm700 ${DATA_DIR}
  /usr/bin/mysql_install_db --user=mysql --basedir=/usr --datadir=${DATA_DIR}
  chown -R mysql:mysql ${DATA_DIR} &> /dev/null
fi

su - mysql -s /bin/sh -c "/usr/bin/mysqld"

# vim:ft=sh et ts=2 sw=2 ai:
